[package]
name = "caxseii/lightbeamsystem"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
knit = "sleitnick/knit@1.6.0"
cmdr = "evaera/cmdr@1.12.0"
component = "sleitnick/component@2.4.8"
janitor = "howmanysmall/janitor@1.15.7"
goodsignal = "stravant/goodsignal@0.2.1"
topbarplus = "etheroit/topbarplus@1.0.1"
zoneplus = "mattschrubb/zoneplus@3.2.0"
timer = "sleitnick/timer@1.1.2"
log = "sleitnick/log@0.1.1"